### ISSUE TITLE
Additional custom fields

### ISSUE THREAD

**Issue by SkyaTura** [carloscuesta/gitmoji-cli#989]
### Description of the problem

Some platforms allow quick actions to apply changes on issues/PRs through specific commands written on commit messages.

### Solution

Allow custom fields to be created with specific prompts or lists to fulfill some template.

For instance:

```
? Choose a gitmoji: ✨  - Introduce new features.
? Enter the commit title [24/48]: Add super awesome button
? Enter the commit message:
? Time spent on this issue: 32h
? The issue is complete already (y/N): y
```
_That is a heck of button_

If the last field is filled, the final commit message would have `/spent 32h` and `/request_review` appended at the end, adding time-tracking features from GitLab.

This could be used for any kind of company patterns.

### Additional context

I think this may be somewhat related to #780, but I chose to create a new one because this concept doesn't exist yet, unlike scopes which is already a feature.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue requesting the same feature.

**Comment by carloscuesta** [comment]
Hey! 👋🏼 

I think this is something we may want to explore as part of the cli. If I understood properly the idea would be to allow users defining custom prompts as part of the CLI configuration. 

In a way that you can "tailor" the prompts according to your workflow, for things that we don't want to bundle as part of the cli itself.

One potential challenge I see with this, is that by introducing this "flexibility" into the cli, it would open the door for people to break it, since there's no way for us to validate user defined custom prompts. 

Also it can be very tricky to know where the "prompt" should be applied (e.g: commit message, commit title etc).

**Comment by SkyaTura** [comment]
This is what I had in mind.

First, this level of customization, at least for 1st versions, should be done at a "config file" level, to avoid overcomplicating the implementation of the settings.

We could work with a template language and a concept of fields, which at least the "emoji", "title" and "message" must be put in place.

That said, take for example the following config (using handlebars.js):

```yaml
custom_commit_message:
  additional_fields:
    - type: text
      name: scope
      label: "Insert the scope of the changes"
      required: false
    - type: list
      name: affected
      multiple: true
      required: false
      options:
        - app
        - api
        - value: other
          text: "Something else"
    - type: boolean
      name: request_review
      label: "Is it ready for code review"
    - type: text
      name: issue
      label: "It closes an open issue"
      condition: request_review
      validation: /GM[0-9]{4}/
    - type: number
      name: spent_hours
      label: "How many hours were spent"
      mask: 0h
      required: true
  template: >-
    {{emoji}} {{#if scope.length}}[{{scope}}]{{/if}} {{title}}

    {{message}}
    
    /spent {{spent_hours}}h
    {{#request_review}}
    /fixes {{issue}}
    /request_review
    {{/request_review}}
```

The input when commit would be:

```
? Choose a gitmoji: 💥 - Introduce new features.
? Enter the commit title [24/48]: Add super awesome button
? Enter the commit message: This button has many features that will change the whole concept of buttons.
? Enter the scope of the changes: 
? Is it ready for code review (y/N): y
? It closes an open issue: GM2134
? How many hours were spent: 32
```

The final output:

```
💥  Add super awesome button

This button has many features that will change the whole concept of buttons.

/spent 32h
/request_review
/fixes GM2134
```
